<Gerenciador>:
    Menu:
        name: 'menu'

    Registrar:
        name: 'registrar'

    Recepcionista:
        name: 'recepcionista'

    Cozinha:
        name: 'cozinha'

    Gerente:
        name: 'gerente'


<Menu>:
    BoxLayout:
        orientation: "vertical"
        canvas:
            Color:
                rgba:0.8, 0.2, 0.1, 1
            Rectangle:
                pos:self.pos
                size:self.size
        padding:root.width*0.20, root.height*0.1
        spacing:"30dp"
        BoxLayout:
            size_hint:None, None
            size:"220dp","180dp"
            Label:
                text:"Restaurante Brasilia"
                font_size:"30sp"
                bold:True
        BoxLayout:
            orientation:"vertical"
            BoxLayout:
                orientation:"vertical"
                size_hint_y:None
                height:"100dp"
                Label:
                    text:"cpf"
                    size_hint_x:None
                    width:"70dp"
                    bold:True
                    id:cpf
                TextInput:
                    hint_text:"Digite seu CPF"
                    size_hint_y:None
                    multiline:False
                    height:"40dp"
                    id:cpfText

        BoxLayout:
            spacing:"40dp"
            padding:0, self.height / 4
            ButtonOk:
                text:"Entrar"
                font_size:"20sp"
                bold:True
                on_release:app.root.current = "recepcionista"
            CadastroButton:
                text:"Cadastrar"
                on_release:app.root.current = "registrar"


<Registrar>:
    BoxLayout:
        orientation:"vertical"
        canvas:
            Color:
                rgba: 1, 0.5, 0.1, 1
            Rectangle:
                pos:self.pos
                size:self.size
        padding:0, "25dp"
        BoxLayout:
            size_hint_y:None
            height:"100dp"
            Label:
                text:"Cadastro"
                font_size:"30sp"
                bold:True
                size_hint_x:None
                id:cadastro
                width:"300dp"
        BoxLayout:
            orientation:"vertical"
            ScrollView:
                BoxLayout:
                    orientation:"vertical"
                    size_hint_y:None
                    height:self.minimum_height
                    padding:root.width*0.20, "10dp"
                    spacing:"30dp"
                    BoxLayout:
                        orientation:"vertical"
                        size_hint_y:None
                        height:"70dp"
                        Label:
                            font_size:"15sp"
                            bold:True
                            text:"Nome"
                            size_hint_x:None
                            width:"150dp"
                            id:nomeRegistro
                        TextInput:
                            id:nomeCadastro
                            hint_text:"Cadastre seu Nome"
                            size_hint_y:None
                            height:"40dp"
                            multiline:False

                    BoxLayout:
                        orientation:"vertical"
                        size_hint_y:None
                        height:"70dp"
                        Label:
                            font_size:"15sp"
                            bold:True
                            text:"CPF"
                            size_hint_x:None
                            width:"150dp"
                            id:cpfRegistro
                        TextInput:
                            id:cpfCadastro
                            hint_text:"Cadastre seu CPF"
                            size_hint_y:None
                            height:"40dp"
                            multiline:False

                    BoxLayout:
                        orientation:"vertical"
                        size_hint_y:None
                        height:"70dp"
                        Label:
                            font_size:"15sp"
                            bold:True
                            text:"Data de Contrato"
                            size_hint_x:None
                            width:"150dp"
                            id:dataRegistro
                        TextInput:
                            id:dataCadastro
                            hint_text:"Digite a data de inicio de seu Contrato"
                            size_hint_y:None
                            height:"40dp"
                            multiline:False
                            password:False

                    BoxLayout:
                        orientation:"vertical"
                        size_hint_y:None
                        height:"70dp"
                        Label:
                            font_size:"15sp"
                            bold:True
                            text:"Digite seu Cargo"
                            size_hint_x:None
                            width:"150dp"
                            id:cargoRegistro
                        TextInput:
                            id:cargoCadastro
                            hint_text:"Digite seu Cargo"
                            size_hint_y:None
                            height:"40dp"
                            multiline:False
                            password:False

            BoxLayout:
                size_hint_y:None
                height:"90dp"
                padding:root.width * 0.36, 0
                ButtonOk:
                    text:"Pronto!"
                    size_hint_y:None
                    height:"60dp"
                    bold:True
                    font_size:"18sp"

<Recepcionista>:
    BoxLayout:
        orientation:"vertical"
        canvas:
            Color:
                rgba: 1, 0.5, 0.1, 1
            Rectangle:
                pos:self.pos
                size:self.size
        padding:0, "25dp"
        BoxLayout:
            orientation:"vertical"

            Image:
                source: 'imagens/recepcionista.jpg'
                size: self.texture_size

            BoxLayout:
                size_hint:None, None
                size:"220dp","180dp"
                pos_hint: {"center_x": 0.4, "center_y": 1}
                padding:root.width*0.20, root.height*0.1
                spacing:"30dp"
                BoxLayout:
                Label:
                    text:"Espaço da recepção"
                    font_size:"30sp"
                    bold:True

            BoxLayout:
                size_hint_y:None
                height:"90dp"
                padding:root.width * 0.36, 0
                spacing: 20
                ButtonOk:
                    text:"Mesas"
                    size_hint_y:None
                    height:"60dp"
                    bold:True
                    font_size:"18sp"

                ButtonOk:
                    text:"Clientes"
                    size_hint_y:None
                    height:"60dp"
                    bold:True
                    font_size:"18sp"

                ButtonOk:
                    text:"sair"
                    size_hint_y:None
                    height:"60dp"
                    bold:True
                    font_size:"18sp"
                    on_release:app.root.current = "menu"


<Cozinha>:
    BoxLayout:
        orientation:"vertical"
        canvas:
            Color:
                rgba: 1, 0.1, 0.1, 1
            Rectangle:
                pos:self.pos
                size:self.size
        padding:0, "25dp"
        BoxLayout:
            orientation:"vertical"

            Image:
                source: 'imagens/chefe.jpg'
                size: self.texture_size

            BoxLayout:
                size_hint:None, None
                size:"220dp","180dp"
                pos_hint: {"center_x": 0.4, "center_y": 1}
                padding:root.width*0.20, root.height*0.1
                spacing:"30dp"
                BoxLayout:
                Label:
                    text:"Espaço da cozinha"
                    font_size:"30sp"
                    bold:True

            BoxLayout:
                orientation: 'vertical'
                size_hint_y:None
                height:"90dp"
                padding:root.width * 0.36, 0
                spacing: 30
                ButtonOk:
                    text:"Receitas"
                    size_hint_y:None
                    height:"30dp"
                    bold:True
                    font_size:"18sp"

                ButtonOk:
                    text:"Ingredientes"
                    size_hint_y:None
                    height:"30dp"
                    bold:True
                    font_size:"18sp"

                ButtonOk:
                    text:"utensílios"
                    size_hint_y:None
                    height:"30dp"
                    bold:True
                    font_size:"18sp"

            BoxLayout:
                size_hint_y:None
                height:"90dp"
                padding:root.width * 0.36, 0
                spacing: 20

                ButtonOk:
                    text:"Sair"
                    size_hint_y:None
                    height:"60dp"
                    bold:True
                    font_size:"18sp"
                    on_release:app.root.current = "menu"


<Gerente>:
    BoxLayout:
        orientation:"vertical"
        canvas:
            Color:
                rgba: 0, 0, 0.5, 1
            Rectangle:
                pos:self.pos
                size:self.size
        padding:0, "25dp"
        BoxLayout:
            orientation:"vertical"

            Image:
                source: 'imagens/gerente.jpg'
                size: self.texture_size

            BoxLayout:
                size_hint:None, None
                size:"220dp","180dp"
                pos_hint: {"center_x": 0.4, "center_y": 1}
                padding:root.width*0.20, root.height*0.1
                spacing:"30dp"
                BoxLayout:
                Label:
                    text:"Administração"
                    font_size:"30sp"
                    bold:True

            BoxLayout:
                orientation: 'vertical'
                size_hint_y:None
                height:"90dp"
                padding:root.width * 0.36, 0
                spacing: 30
                ButtonOk:
                    text:"Fornecedores"
                    size_hint_y:None
                    height:"30dp"
                    bold:True
                    font_size:"18sp"

                ButtonOk:
                    text:"Funcionarios"
                    size_hint_y:None
                    height:"30dp"
                    bold:True
                    font_size:"18sp"

                ButtonOk:
                    text:"utensílios"
                    size_hint_y:None
                    height:"30dp"
                    bold:True
                    font_size:"18sp"

            BoxLayout:
                size_hint_y:None
                height:"90dp"
                padding:root.width * 0.36, 0
                spacing: 20

                ButtonOk:
                    text:"Sair"
                    size_hint_y:None
                    height:"60dp"
                    bold:True
                    font_size:"18sp"
                    on_release:app.root.current = "menu"





<ButtonOk@ButtonBehavior+Label>:
    canvas.before:
        Color:
            rgba:1, .7, 0, 1
        RoundedRectangle:
            pos:self.pos
            size:self.size
            radius:[20]
<CadastroButton@ButtonBehavior+Label>:
    color: 0, 1, 1, 1
    font_size: "20sp"
    bold: True